name: CI Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run training
        run: |
          python src/train.py
      - name: Export ONNX
        run: |
          python src/export_onnx.py
      - name: Register Model
        run: |
          python src/register_model.py
